Project 1: Creating a Replica of NYT Page
krishnzzz/Project-1 pull request #6
Opened 2020-10-22 14:21 UTC by krishnzzz

In the creation of a replica of the NYT Page, the following tasks were done:

- Create index.html
- Create style.css and link to HTML
- Gather all required texts, icons, images and fonts from the page.
- Create a proper folder structure to retrieve assets easily.
- Include all required contents of the page in the index.html file using proper HTML5 Semantics.
- Create required font-faces for the texts of the page.
- Add all required styling like color, font-size, font-family, font-weight, text-decoration, width & height and margin & padding to make the page look as similar to the original as possible.
- Include required display attributes where needed.
- Place all items at the required positions.
- Include favicon.
- Check for and fix according to linter requirements.

A few items have not been included like exact hrefs to anchors, and a few minor stylings due to time constraints.

Most of the works have been done in proper collaboration by both partners working on the project.

Thank You.

2020-10-22 17:03 UTC, rammazzoti2000 requested changes
### Hello @krishnzzz and @rayking12 :wave: well done on this project
The project is well built, most of the HTML code is semantic, pull request is descriptive, commits are short and meaningful.

As you would expect there are a few issues to fix before approving the project, but nothing major, please follow the comments bellow :point_down: 

### :stop_sign: Required Changes :construction: :construction_worker:
- [x] The README.md file should be a bit more descriptive, add a screenshot. Take a look at mine to have a clearer idea on how it should be :point_right: [link here](https://github.com/rammazzoti2000/Positioning-and-Floating-Elements/blob/master/README.md)
- [x] The main content of the page is wrapped in a `<article>` tag, that is semantically wrong, please change it to a `<main>` tag.
- [x] If the `<a>` tag contains an empty link that link should be marked with a `#` symbol. Please for dead links use `<a href="#">` 
- [ ] It uses [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)). Since the website change a bit in its structure the `Editor's picks` is now placed under `More in Space and Astronomy`.

## Optional:
In your project, each `<section>` tag contains `<div>` containers for the actual text (article?) in the main content. You could use `<article>` tag for each container to improve the HTML semantic.

### <em>Kindly fix the REQUIRED issues and send for another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of ```@ale[x360]``` if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +      <svg viewBox="0 0 184 25" fill="#000"><path d="M13.8 2.9c0-2-1.9-2.5-3.4-2.5v.3c.9 0 1.6.3 1.6 1 0 .4-.3 1-1.2 1-.7 0-2.2-.4-3.3-.8C6.2 1.4 5 1 4 1 2 1 .6 2.5.6 4.2c0 1.5 1.1 2 1.5 2.2l.1-.2c-.
The NY Times image logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)), please wrap it with an `<a></a>` element

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +  <article>
This `<article>` tag should be renamed to `<main>` since it contains the main content on the page, and makes use of HTML semantic.

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +              <a href="">
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <a href="">Rudy Giuliani Denies He Did Anything Wrong in New ‘Borat’ Movie</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <a href="">Corrections</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <a href="">Video: Opinion</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <a href="">Video: Arts</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <a href="">Travel</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <a href="">Manage My Account</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <a href="">中文网</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +      <a href="">Subscriptions</a>
Please use a dead link, no empty `href` attributes => `<a href="#">`

2020-10-22 17:03 UTC, rammazzoti2000 commented on index.html
> +        <section class="editor-pick">
It uses [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
Since the website changed a bit in its structure the `Editor's picks` is now placed under `More in Space and Astronomy`.

2020-10-23 11:11 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @krishnzzz and @rayking12 :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

- **Tip**: You can actually show your screenshot in your Readme file by typing [!screenshot](URL). It's better than a link, as it is right now :wink:

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-23 12:09 UTC, merged